import json
import os
import re
import sys
import time
from typing import Any

from openai import OpenAI

from src.utils.common import create_module_logger
from src.utils.ros_executor import RosExecutor

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../../"))
)
from dotenv import load_dotenv

from ithor.handlers.action import Action

load_dotenv()
logger = create_module_logger(__name__, module_log=True)
openai_api_key = os.environ.get("OPENAI_API_KEY")
if not openai_api_key:
    logger.error("OPENAI_API_KEY not found in environment variables.")
    raise EnvironmentError("OPENAI_API_KEY not found in environment variables.")

client = OpenAI(api_key=openai_api_key)


class ProgPromptActionFailedError(Exception):
    """Exception raised when an action fails in the progprompt simulation."""

    def __init__(self, action_name: str, args: tuple, message: str):
        self.action_name = action_name
        self.args = args
        self.message = message
        super().__init__(f"Action '{action_name}' with args {args} failed: {message}")


class PlanSyntaxError(Exception):
    """Exception raised when the LLM-generated plan has a Python syntax error."""

    pass


def LM(
    prompt,
    gpt_version,
    max_tokens=128,
    temperature=0,
    stop=None,
    logprobs=True,
    frequency_penalty=0,
):
    ## function to query LM ##
    # you may adjust the genration parameters as needed
    # more info on parameters here:
    # https://platform.openai.com/docs/api-reference/completions/create

    message = [
        {
            "role": "system",
            "content": "You are a highly intelligent and context-aware Household AI Robot Assistant.",
        },
        {
            "role": "user",
            "content": f"{prompt}"
            "1. Respond only with the `def` function code. "
            "2. Do not include triple quotes (```) or the word 'python' in your response."
            "3. It should follow the format of the example I gave."
            "4. assert&else can be utilized aggressively."
            "5. Do not write iteration statements(ex. for, while) for iterations. If you must repeat it, write it in full."
            "6. Object name must be exactly the same."
            "7. Ensure all function calls are syntactically correct, complete with all required arguments and closing parentheses.",
        },
    ]
    logger.info(f"LM PROMPT:\n\n{message}\n")
    response = client.chat.completions.create(
        model=gpt_version,
        messages=message,
        max_tokens=max_tokens,
        temperature=temperature,
        # stop=stop,
        logprobs=logprobs,
        frequency_penalty=frequency_penalty,
    )

    return response, response.choices[0].message.content.strip().replace(
        "```python", ""
    ).replace("```", "")


def LM_assert(
    prompt,
    gpt_version,
    max_tokens=2,
    temperature=0,
    stop=None,
    logprobs=True,
    frequency_penalty=0,
):
    ## function to query LM ##
    # you may adjust the genration parameters as needed
    # more info on parameters here:
    # https://platform.openai.com/docs/api-reference/completions/create

    message = [
        {
            "role": "system",
            "content": "You are a helpful assistant. just give me only word 'True' or 'False'",
        },
        {"role": "user", "content": f"{prompt}"},
    ]
    logger.info(f"LM_assert PROMPT:\n\n{message}\n")

    response = client.chat.completions.create(
        model=gpt_version,
        messages=message,
        max_tokens=max_tokens,
        temperature=temperature,
        # stop=stop,
        logprobs=logprobs,
        frequency_penalty=frequency_penalty,
    )

    return response, response.choices[0].message.content.strip()


def fun_processing(plan: str) -> dict:
    """Parse the LLM-generated plan into a structured format.

    This function processes a multi-line string representing a plan,
    organizing it into subgoals. It specifically handles the custom
    `assert`/`else` syntax by grouping recovery actions (`else`)
    under their corresponding condition check (`assert`).

    Args:
        plan: The string containing the plan generated by the LLM.

    Returns:
        A dictionary where keys are subgoal names and values are lists
        of actions. Normal actions are strings, while assert/else blocks
        are represented as dictionaries: `{'assert': str, 'else': [str]}`.
    """

    subgoals = {}
    sg = "0"  # Default subgoal key
    subgoals[sg] = []

    lines = plan.split("\n")
    for line in lines:
        stripped_line = line.strip()

        if not stripped_line or "def" in stripped_line:
            continue

        if stripped_line.startswith("#"):
            sg = stripped_line.lstrip("#").strip()
            if sg not in subgoals:
                subgoals[sg] = []
        elif stripped_line.startswith("assert"):
            assert_block = {"assert": stripped_line, "else": []}
            subgoals[sg].append(assert_block)
        elif stripped_line.startswith("else:"):
            # Find the last added assert block in the current subgoal
            if (
                subgoals[sg]
                and isinstance(subgoals[sg][-1], dict)
                and "assert" in subgoals[sg][-1]
            ):
                else_action = stripped_line.split(":", 1)[1].strip()
                subgoals[sg][-1]["else"].append(else_action)
            else:
                # Orphaned 'else', log warning and skip or handle as error
                logger.warning(
                    f"Orphaned 'else' statement found: {stripped_line}. Ignoring."
                )
        else:
            subgoals[sg].append(stripped_line)

    # Remove empty default subgoal if it was not used
    if sg != "0" and not subgoals.get("0"):
        if "0" in subgoals:
            del subgoals["0"]

    print(subgoals)
    return subgoals


def find_objID(controller, obj_type: str) -> str | None:
    """Find object ID by matching object type (exact match).

    This function assumes a fully-observable environment and searches all
    objects. It includes special handling for 'Sink' to find a 'SinkBasin'.

    Args:
        controller: AI2Thor controller.
        obj_type: Object type name to search for (e.g., 'Sink', 'Pot').

    Returns:
        The object ID if a match is found, otherwise None.
    """
    if not obj_type:
        return None

    obj_type_lower = obj_type.lower()
    all_objects = controller.last_event.metadata["objects"]

    # Special handling for 'sink' -> find a 'sinkbasin'
    if obj_type_lower == "sink":
        logger.info("Query is for 'Sink', redirecting to find 'SinkBasin'.")
        for obj in all_objects:
            if obj["objectType"] == "SinkBasin":
                logger.info(f"Found SinkBasin with ID '{obj['objectId']}'.")
                return obj["objectId"]
        logger.warning("Could not find any SinkBasin in the scene.")
        return None

    # Normal object search (exact match)
    for obj in all_objects:
        if obj["objectType"].lower() == obj_type_lower:
            return obj["objectId"]

    return None


def last_action_success(controller):  ## 마지막 행동이 성공했는지 확인
    if controller.last_event.metadata["lastActionSuccess"]:
        return True
    else:
        return False


def see_have_ros():
    """Read object states from ROS dynamic state file for real-world execution."""
    with open("assets/runtime_state/dynamic/object_states.json", "r") as f:
        data = json.load(f)
    objs = ""
    for obj in data.keys():
        objs += f"{obj} is {data[obj]}\n"
    return objs


def see_have(controller):  ## assert 및 해야할 행동

    controller.step(action="Pass")
    data = controller.last_event.metadata

    # agent가 있는 방 name
    # agent가 가지고 있는 object 이름 및 ID
    inventory_objects = data["inventoryObjects"]
    if inventory_objects:
        agent_has_obj = [obj["objectType"] for obj in inventory_objects]
    else:
        agent_has_obj = ""
    # agent와 가까이 있는 object 이름 및 ID
    # ai2thor 에서는 controller을 정의할 때 visibilityDistance를 정의하는데
    # 사실상 visible=true 라는건 볼 수 있고, 가까운걸로 보는게 좋을 것 같음
    obj_ids = dict(
        [
            (obj["objectId"], obj["objectType"])
            for obj in data["objects"]
            if obj["visible"]
        ]
    )
    # relation 뽑아내기. receptacle을 holds로 바꿈. ex) fridge holds egg
    # 관계를 저장할 리스트
    relations = []

    # obj_ids에서 각 객체를 확인
    for obj_id, obj_type in obj_ids.items():
        # obj_ids에서 해당 objectId로 객체 찾기
        obj = next((obj for obj in data["objects"] if obj["objectId"] == obj_id), None)
        if obj is None:
            continue

        receptacle_ids = obj.get("receptacleObjectIds", [])

        if receptacle_ids:  # receptacleObjectIds가 비어 있지 않으면
            for receptacle_id in receptacle_ids:
                # receptacle_id에 해당하는 objectType을 전체 metadata에서 찾아서 사용
                receptacle_obj = next(
                    (
                        obj
                        for obj in data["objects"]
                        if obj["objectId"] == receptacle_id
                    ),
                    None,
                )

                if receptacle_obj:
                    # 'holds' 관계 생성
                    relation = f"{obj_ids[obj_id]} holds {receptacle_obj['objectType']}"
                    relations.append(relation)
                else:
                    print(
                        f"Warning: receptacleId {receptacle_id} not found in metadata"
                    )

    # 이젠 state 뽑아낼거임(obj)
    objs = []
    # 속성 리스트
    properties = [
        # "isInteractable",
        "isToggled",
        "isBroken",
        "isFilledWithLiquid",
        "isDirty",
        "isUsedUp",
        "isCooked",
        "isHeatSource",
        "isColdSource",
        "isSliced",
        "isOpen",
        "isPickedUp",
        "isMoving",
    ]

    # 속성 체크를 위해 각 객체를 한 번만 처리
    for obj in data["objects"]:
        # obj_ids에 있는 객체만 처리
        if obj["objectId"] not in obj_ids or not obj["visible"]:
            continue

        object_type = obj_ids[obj["objectId"]]  # objectId로 objectType을 얻음
        ob_states = [object_type, []]  # [objectType, 속성 목록]

        # 각 속성에 대해 체크
        for prop in properties:
            if (
                prop == "isOpen"
                and obj.get(prop, False) is False
                and obj.get("openable", False) is True
            ):
                ob_states[1].append("isClosed")
            elif (
                prop == "isToggled"
                and obj.get(prop, False) is False
                and obj.get("toggleable", False) is True
            ):
                ob_states[1].append("isToggledOff")
            elif obj.get(prop, False):  # 속성이 True인 경우
                ob_states[1].append(prop)

        # 속성이 하나라도 있다면 문자열로 추가
        if ob_states[1]:
            objs.append(f"{ob_states[0]} is {' and '.join(ob_states[1])}")
        else:
            # 속성이 모두 False인 경우 object 이름만 추가
            objs.append(ob_states[0])

    objs = ", ".join(objs)
    objs = list(set(objs.split(", ")))
    # 빈 문자열 제거
    objs = [ob for ob in objs if len(ob) > 0]

    # obj들의 상태를 다시 ,로 연결하고, 다른 obj들과 relation들도 ,로 연결
    objs = ", ".join(objs) + ", " + ", ".join(relations) + ". "
    # 지금 갖고있는 obj들도 objs에 추가
    if len(agent_has_obj) > 0:
        agent_has_obj = ", ".join(agent_has_obj)
        objs += f" You have {agent_has_obj}. "

    return objs


def get_current_state_prompt():
    ## fixed function to define "PROMPT for state check"
    ## current state 는 state \n\n assert로 구성되어 있음
    current_state_prompt = "kitchencounterdrawer, door is OPEN, character, wallpictureframe, clothespile is CLOSED, coffeemaker is OFF, pie, wall, bedroom, microwave is OFF and CLOSED, lightswitch is ON, kitchencabinet is CLOSED, washingsponge, bellpepper, salmon, fridge is CLOSED, wallshelf, tvstand, paper, floor, chips, photoframe, kitchen, whippedcream, candybar, faucet is OFF, tv is OFF, cereal, stovefan, waterglass, cutleryknife, kitchentable, condimentbottle, wineglass, bookshelf, cutleryfork, chocolatesyrup, walllamp, bench, sink, crackers, orchid, condimentshaker, kitchencounter is CLOSED, livingroom, powersocket, coffeepot is CLOSED, creamybuns, ceilinglamp, rug, book is CLOSED, plate, toaster is OFF, clock is OFF, wallphone is OFF, ceiling, fryingpan, box is CLOSED, dishbowl, bananas, breadslice, bathroom, garbagecan is CLOSED, stove is OFF and CLOSED, dishwashingliquid, plate ON kitchencounter, cutleryfork ON kitchentable, bookshelf ON floor, cutleryknife ON kitchentable, bellpepper ON kitchencounter, microwave ON kitchencounterdrawer, chocolatesyrup ON wallshelf, whippedcream ON rug, salmon ON microwave, orchid ON tvstand, wallpictureframe ON wall, bench ON floor, tvstand ON floor, book INSIDE bookshelf, bananas ON dishbowl, toaster ON kitchencounterdrawer, whippedcream ON kitchentable, dishbowl INSIDE bookshelf, fryingpan ON stove, rug ON kitchentable, coffeepot INSIDE coffeemaker, waterglass ON rug, dishwashingliquid ON kitchencounter, wallshelf ON wall, washingsponge ON kitchencounter, clothespile INSIDE bookshelf, bananas INSIDE bookshelf, box ON bookshelf, plate ON kitchentable, waterglass ON kitchentable, creamybuns ON wallshelf, breadslice INSIDE toaster, coffeemaker ON kitchencounterdrawer, chips ON wallshelf, book ON kitchentable, dishbowl ON bookshelf, pie ON kitchentable, wineglass ON tvstand, box ON tvstand, coffeepot ON kitchencounter, bellpepper ON kitchencounterdrawer, condimentshaker INSIDE bookshelf, coffeemaker ON kitchencounter, toaster ON kitchencounter, box INSIDE bookshelf, crackers ON wallshelf, character HOLD_RH book, faucet ON kitchencounter, book ON rug, cereal ON wallshelf, plate INSIDE microwave, candybar ON wallshelf, condimentbottle INSIDE bookshelf, tv ON tvstand, microwave ON kitchencounter, paper INSIDE bookshelf, kitchencounterdrawer ON kitchencounter, fridge ON floor, photoframe ON tvstand, wallpictureframe ON wallpictureframe, bench ON rug, pie ON rug, kitchencounterdrawer ON kitchencounterdrawer, dishbowl ON kitchencounter.\n\nassert('close' to 'mug' )\nFalse\nassert('close' to 'microwave' )\nTrue\nassert('book' is 'closed' )\nTrue\nassert('lightswitch' is 'OFF')\nFalse\nassert('book' in 'bookshelf')\nTrue\nassert('book' in 'hands')\nTrue\nassert('cereal' on 'bookshelf')\nFalse"
    objs = ["microwave", "book", "lightswitch", "bookshelf", "cereal"]
    state, asserts = current_state_prompt = current_state_prompt.split("\n\n")
    state = state.split(",")
    state = "You see: " + ", ".join(
        [
            i.strip() for i in state if any(element in i for element in objs)
        ]  # obj에 있는 element가 state에 있는 i 에 있으면 추가. 현재 scene 에 관련 있는 obj들만 뽑으려고 함
    )
    current_state_prompt = f"{state}\n\n{asserts}"
    return current_state_prompt


current_state_prompt = get_current_state_prompt()


def parse_prog_to_ros(action_str: str) -> str:
    """Convert progprompt action syntax to ROS executor syntax.

    Args:
        action_str: e.g., "walk(kitchen)", "put(apple, table)"

    Returns:
        str: e.g., "navigate_to kitchen", "place_on_top table"
    """
    parsed_action = re.findall(r"(\w+)\s*\((.*)\)", action_str)
    if not parsed_action:
        return action_str

    action_name, action_arg_str = parsed_action[0]
    action_args = [arg.strip().strip("'\"") for arg in action_arg_str.split(",")]
    action_args = [arg for arg in action_args if arg]

    action_map = {
        "walk": "navigate_to",
        "pickup": "grasp",
        "open": "open",
        "close": "close",
        "toggle_on": "toggle_on",
        "toggle_off": "toggle_off",
        "wait": "wait",
        "slice": "slice",
    }

    if action_name == "put":
        target = action_args[1] if len(action_args) >= 2 else action_args[0] if action_args else ""
        return f"place_on_top {target}"

    if action_name in action_map:
        ros_cmd = action_map[action_name]
        arg = action_args[0] if action_args else ("0" if action_name == "wait" else "")
        return f"{ros_cmd} {arg}"

    return f"{action_name} {' '.join(action_args)}"


def _execute_single_action(
    action_str: str,
    action_interface: Any,
    controller,
    log_file,
    elapsed_time: float,
    is_ros: bool = False,
) -> float:
    """Execute a single action string and handle logging and errors."""
    if is_ros:
        try:
            log_file.write(f"Executing: {action_str}\n")
            ros_action = parse_prog_to_ros(action_str)
            log_file.write(
                f"INFO: Converted '{action_str}' to ROS action '{ros_action}'\n"
            )
            success, duration, logs = action_interface.execute_primitive_actions(
                [ros_action]
            )
            if not success:
                raise RuntimeError(f"ROS Action '{ros_action}' failed.")
            log_file.write(f"Action '{action_str}' completed in {duration:.2f}s\n")
            return elapsed_time + duration
        except Exception as e:
            log_file.write(f"ERROR executing ROS action '{action_str}': {e}\n")
            raise

    # This regex handles func('arg'), func ( 'arg' ), func(arg), and func()
    parsed_action = re.findall(r"(\w+)\s*\((.*)\)", action_str)
    if not parsed_action:
        log_file.write(f"ERROR: Could not parse action: {action_str}\n")
        raise ValueError(f"Could not parse action: {action_str}")

    action_name, action_arg_str = parsed_action[0]
    # Handle cases with empty args like drop() and strip quotes/spaces
    action_args = (
        [arg.strip().strip("'\"") for arg in action_arg_str.split(",")]
        if action_arg_str
        else []
    )
    target_obj_name = action_args[0] if action_args else None

    log_file.write(f"Executing: {action_str}\n")
    start_time = time.time()
    action_result = None

    try:
        # Handle parameterless actions or actions with non-object args first
        if action_name == "drop":
            action_result = action_interface.drop()
        elif action_name == "wait":
            duration = float(target_obj_name) if target_obj_name else 0.0
            action_result = action_interface.wait(duration)
        else:
            # All other actions require an object ID
            if not target_obj_name:
                raise ValueError(
                    f"Action '{action_name}' requires an object argument, but none was provided."
                )

            # --- Target Refinement (Sink -> SinkBasin) ---
            # For 'put' actions targeting a 'Sink', we must target 'SinkBasin' instead.
            if action_name == "put" and "sink" in target_obj_name.lower():
                log_file.write(
                    f"INFO: Refining target from '{target_obj_name}' to 'SinkBasin' for put action.\n"
                )
                target_obj_name = "SinkBasin"
            # --- End of Target Refinement ---

            # Now, get the object ID for the actual action
            log_file.write(
                f"INFO: Searching for object ID for target '{target_obj_name}'.\n"
            )
            target_obj_id = find_objID(controller, target_obj_name)
            if not target_obj_id:
                log_file.write(
                    f"ERROR: Could not find object ID for target '{target_obj_name}'.\n"
                )
                raise RuntimeError(
                    f"Action failed: Could not find object ID for '{target_obj_name}'."
                )
            log_file.write(
                f"INFO: Found object ID '{target_obj_id}' for target '{target_obj_name}'.\n"
            )

            # Map plan action names to handler methods and execute with the ID
            action_map = {
                "walk": action_interface.move_to,
                "pickup": action_interface.pickup,
                "put": action_interface.put,
                "open": action_interface.open,
                "close": action_interface.close,
                "toggle_on": action_interface.toggle_on,
                "toggle_off": action_interface.toggle_off,
                "slice": action_interface.slice,
            }

            if action_name in action_map:
                action_result = action_map[action_name](target_obj_id)
            else:
                raise ValueError(f"Unknown action: {action_name}")

        # Check for failure
        if action_result is False:
            raise RuntimeError(f"Action '{action_str}' returned failure from handler.")

    except (ValueError, RuntimeError, TypeError) as e:
        log_file.write(f"ERROR executing action '{action_str}': {e}\n")
        raise

    end_time = time.time()
    action_duration = end_time - start_time
    if isinstance(action_result, (int, float)):
        action_duration += action_result  # Add time from simulation (e.g., wait)

    log_file.write(f"Action '{action_str}' completed in {action_duration:.2f}s\n")
    return elapsed_time + action_duration


def simulate_execution(
    controller, test_tasks, gen_plan, log_file, args, logger, action_interface: Any
):
    elapsed_time = 0
    is_ros = getattr(args, "ros", False)

    for task, plan in zip(test_tasks, gen_plan):
        log_file.write(f"Starting simulation for task: {task}\n")
        # Log the raw plan received from the LLM before any processing
        log_file.write(
            f"--- RAW PLAN RECEIVED ---\n{plan}\n-------------------------\n"
        )
        logger.info(f"Raw plan for task '{task}':\n{plan}")
        try:
            subgoals = fun_processing(plan)
        except Exception as e:
            log_file.write(
                f"CRITICAL: Plan parsing failed with an unexpected error. Error: {e}\n"
            )
            logger.error(f"Plan parsing failed. Error: {e}", exc_info=True)
            raise ProgPromptActionFailedError(
                action_name="Plan Parsing", args=(), message=str(e)
            )

        for subgoal in subgoals.keys():
            step = 1
            for action_item in subgoals[subgoal]:
                if step > 50:  # Safety break for long or looping plans
                    log_file.write("WARNING: Exceeded step limit for subgoal.\n")
                    break

                if isinstance(action_item, dict):
                    # It's an assert/else block
                    assert_statement = action_item["assert"]

                    # Execute the assert
                    objs = see_have_ros() if controller is None else see_have(controller)
                    state = "You see: " + objs
                    current_state = (
                        f"{current_state_prompt}\n\n{state}\n\n{assert_statement}\n"
                    )
                    _, check_state = LM_assert(
                        current_state, args.gpt_version, max_tokens=2, stop=["\n"]
                    )

                    log_file.write(
                        f"State check:\n{state}\n{assert_statement}\n{check_state.strip()}\n"
                    )

                    if "False" in check_state:
                        log_file.write("Assert failed. Executing recovery actions.\n")
                        for else_action in action_item["else"]:
                            elapsed_time = _execute_single_action(
                                else_action,
                                action_interface,
                                controller,
                                log_file,
                                elapsed_time,
                                is_ros=is_ros,
                            )
                            step += 1
                    else:
                        log_file.write("Assert passed. Skipping recovery actions.\n")

                elif isinstance(action_item, str):
                    # It's a simple action string
                    elapsed_time = _execute_single_action(
                        action_item,
                        action_interface,
                        controller,
                        log_file,
                        elapsed_time,
                        is_ros=is_ros,
                    )
                    step += 1

    print(f"{round(elapsed_time, 2)=}")
    log_file.write(f"Total time spent : {round(elapsed_time, 2)}")
